name: CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: copy files
        run: |
          sudo mkdir /app
          sudo cp * /app

      - name: install pre-requirements
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install yq
      - name: run yp command
        run: yq e '.secrets | to_entries[] | .key + "/" + (.value | to_entries[] | " " + (.key + "=" + .value))' ./app/secrets.yaml | xargs -L 1 vault kv put secret/data/

      - name: Build Docker Image
        run: |
          docker build -t mhthrh/vault:v1.0.1
          docker push mhthrh/vault:v1.0.1

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
         docker build -t  mhthrh/vault:v1.0.1
         docker push  mhthrh/vault:v1.0.1